# Generated by Django 4.0 on 2021-12-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parks',
            fields=[
                ('ParkId', models.AutoField(primary_key=True, serialize=False)),
                ('ParkName', models.CharField(max_length=100)),
                ('ParkLocation', models.CharField(max_length=100)),
                ('ParkSeason', models.CharField(max_length=100)),
                ('ParkHours', models.CharField(max_length=100)),
                ('ParkCapacity', models.PositiveIntegerField()),
                ('ParkCost', models.PositiveIntegerField()),
                ('ParkParkingAvailable', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('VisitorId', models.AutoField(primary_key=True, serialize=False)),
                ('VisitorName', models.CharField(max_length=100)),
                ('ParkId', models.CharField(max_length=100)),
                ('DateOfReservation', models.DateField()),
                ('NumberOfGuests', models.PositiveSmallIntegerField()),
                ('PhotoFileName', models.CharField(max_length=100)),
                ('VisitorEmail', models.CharField(max_length=100)),
                ('visitorPhone', models.CharField(max_length=100)),
            ],
        ),
    ]
