# Generated by Django 4.0 on 2021-12-20 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParkApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitors',
            old_name='visitorPhone',
            new_name='VisitorPhone',
        ),
    ]
