# Generated by Django 4.0 on 2022-01-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkApp', '0003_alter_visitors_parkid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parks',
            name='ParkCost',
            field=models.FloatField(),
        ),
    ]
